name: coiled-coiled-default
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20210324.2
  - aiobotocore=1.4.0
  - aiohttp=3.7.4.post0
  - aioitertools=0.8.0
  - arrow-cpp=5.0.0
  - asgiref=3.4.1
  - async-timeout=3.0.1
  - atk-1.0=2.36.0
  - attrs=21.2.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blosc=1.21.0
  - bokeh=2.3.3
  - botocore=1.20.106
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.0
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.8.1
  - dask-core=2021.8.1
  - dask-glm=0.2.0
  - dask-image=0.6.0
  - dask-ml=1.9.0
  - dask-sql=0.3.9
  - distributed=2021.8.1
  - expat=2.4.1
  - fastapi=0.68.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=2021.7.0
  - gdk-pixbuf=2.42.6
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - graphite2=1.3.13
  - graphviz=2.48.0
  - grpc-cpp=1.39.1
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.12.0
  - h5py=3.3.0
  - harfbuzz=2.9.0
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icu=68.1
  - idna=3.1
  - imagecodecs=2021.7.30
  - jinja2=3.0.1
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - jpype1=1.3.0
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgd=2.3.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - librsvg=2.50.7
  - libssh2=1.9.0
  - libthrift=0.14.2
  - libtiff=4.3.0
  - libtool=2.4.6
  - libutf8proc=2.6.1
  - libwebp=1.2.1
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - llvm-openmp=12.0.1
  - llvmlite=0.36.0
  - locket=0.2.0
  - lz4=3.1.3
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - multipledispatch=0.6.0
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - numba=0.53.1
  - numpy=1.21.2
  - olefile=0.46
  - openjdk=11.0.9.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - orc=1.6.10
  - packaging=21.0
  - pandas=1.3.2
  - pango=1.48.9
  - parquet-cpp=1.5.1
  - partd=1.2.0
  - pcre=8.45
  - pillow=8.3.1
  - pims=0.5
  - pip=21.2.4
  - pixman=0.40.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.8.0
  - pyarrow=5.0.0
  - pycparser=2.20
  - pydantic=1.8.2
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - python=3.9.6
  - python-blosc=1.10.2
  - python-dateutil=2.8.2
  - python-graphviz=0.17
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - re2=2021.08.01
  - readline=8.1
  - requests=2.26.0
  - s3fs=2021.8.0
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - setuptools=57.4.0
  - six=1.16.0
  - slicerator=1.0.0
  - snappy=1.1.8
  - sortedcontainers=2.4.0
  - sqlite=3.36.0
  - starlette=0.14.2
  - tblib=1.7.0
  - threadpoolctl=2.2.0
  - tifffile=2021.8.8
  - tk=8.6.11
  - toolz=0.11.1
  - tornado=6.1
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - tzlocal=3.0
  - urllib3=1.26.6
  - uvicorn=0.15.0
  - wcwidth=0.2.5
  - wheel=0.37.0
  - wrapt=1.12.1
  - xarray=0.19.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zfp=0.5.5
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - altair==4.1.0
    - appnope==0.1.2
    - argon2-cffi==21.1.0
    - astor==0.8.1
    - backcall==0.2.0
    - backoff==1.11.1
    - base58==2.1.0
    - bleach==4.1.0
    - blinker==1.4
    - boto3==1.17.106
    - cachetools==4.2.4
    - click==7.1.2
    - coiled==0.0.50
    - colorama==0.4.4
    - commonmark==0.9.1
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - gitdb==4.0.7
    - gitpython==3.1.24
    - htmlmin==0.1.12
    - imagehash==4.2.1
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jsonschema==4.0.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - matplotlib-inline==0.1.2
    - missingno==0.5.0
    - mistune==0.8.4
    - multimethod==1.6
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - networkx==2.6.3
    - notebook==6.4.4
    - pandas-profiling==3.1.0
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - phik==0.12.0
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - protobuf==3.18.0
    - ptyprocess==0.7.0
    - pydeck==0.7.0
    - pyrsistent==0.18.0
    - pywavelets==1.1.1
    - rich==10.7.0
    - s3transfer==0.4.2
    - seaborn==0.11.2
    - send2trash==1.8.0
    - smmap==4.0.0
    - streamlit==0.89.0
    - streamlit-ace==0.1.0
    - streamlit-pandas-profiling==0.1.2
    - tangled-up-in-unicode==0.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - toml==0.10.2
    - tqdm==4.62.3
    - traitlets==5.0.5
    - validators==0.18.2
    - visions==0.7.4
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
